import Fastify from "fastify";import cors from "@fastify/cors";import { randomUUID, createHash } from "node:crypto";import { prisma } from "./db/prisma.js";import { MIN_VIEW_SECONDS } from "@9527/shared";
const app=Fastify({logger:true});await app.register(cors,{origin:true});const ok=(data:any)=>({ok:true,data});const err=(code:string,message:string,status=400)=>({status,body:{ok:false,error:{code,message}}});
async function user(req:any){const h=req.headers.authorization||"";const token=h.replace("Bearer ","");if(!token)throw new Error("Missing token");const u=await prisma.user.findFirst({where:{id:token.replace(/^token_/,"user_")}}); if(u)return u; const byId=await prisma.user.findUnique({where:{id:token}}); if(byId)return byId; throw new Error("Invalid token")}
app.post("/v1/init",async(req:any)=>{const id="user_"+randomUUID();const deviceId="dev_"+randomUUID();const b=req.body||{};await prisma.user.create({data:{id,account:{create:{}}}});await prisma.device.create({data:{id:deviceId,userId:id,deviceHash:b.deviceHash||deviceId,os:b.os,cliVersion:b.cliVersion}});return ok({userId:id,deviceId,apiToken:id})});
app.get("/v1/me",async(req)=>ok(await user(req)));
app.post("/v1/campaigns/next",async()=>ok({campaign:await prisma.campaign.findFirst({where:{status:"active"},select:{id:true,sponsorName:true,headline:true,body:true,targetUrl:true,rewardPoints:true,status:true}})}));
app.post("/v1/ad-sessions",async(req:any)=>{const u=await user(req);const b=req.body;const dev=await prisma.device.findFirst({where:{id:b.deviceId,userId:u.id}});if(!dev)return err("DEVICE_NOT_FOUND","Device not found",404).body;const camp=await prisma.campaign.findUniqueOrThrow({where:{id:b.campaignId}});const s=await prisma.adSession.create({data:{id:"ads_"+randomUUID(),userId:u.id,deviceId:dev.id,campaignId:camp.id,rewardPoints:camp.rewardPoints,context:b.context,expiresAt:new Date(Date.now()+30*60*1000),ipHash:createHash("sha256").update(req.ip||"").digest("hex"),userAgent:req.headers["user-agent"]}});return ok({sessionId:s.id,landingUrl:`${process.env.WEB_BASE_URL||"http://localhost:3001"}/a/${s.id}`,expiresAt:s.expiresAt})});
for(const ev of ["shown","viewed","clicked"]){app.post(`/v1/ad-sessions/:id/${ev}`,async(req:any)=>{const u=await user(req);const field=(ev+"At") as any;const s=await prisma.adSession.update({where:{id:req.params.id},data:{[field]:new Date(),status:ev}});if(s.userId!==u.id)throw new Error("Forbidden");return ok({session:s})})}
app.get("/v1/ad-sessions/:id",async(req:any)=>ok({session:await prisma.adSession.findUnique({where:{id:req.params.id},include:{campaign:true}})}));
app.post("/v1/ad-sessions/:id/completed",async(req:any)=>{const u=await user(req);const s=await prisma.adSession.findUnique({where:{id:req.params.id},include:{campaign:true}});if(!s||s.userId!==u.id)return err("NOT_FOUND","Session not found",404).body;if(s.rewardedAt)return err("ALREADY_REWARDED","Session already rewarded",409).body;if(s.expiresAt<new Date())return err("EXPIRED","Session expired",400).body;if(!s.viewedAt||Date.now()-s.viewedAt.getTime()<MIN_VIEW_SECONDS*1000)return err("TOO_EARLY","Stay for at least 20 seconds",400).body;if(s.campaign.status!=="active")return err("CAMPAIGN_INACTIVE","Campaign inactive",400).body;const hour=new Date(Date.now()-3600_000);const count=await prisma.adSession.count({where:{userId:u.id,rewardedAt:{gte:hour}}});if(count>=5)return err("RATE_LIMITED","Too many reward attempts",429).body;const result=await prisma.$transaction(async(tx)=>{const fresh=await tx.adSession.findUniqueOrThrow({where:{id:s.id}});if(fresh.rewardedAt)throw new Error("Already rewarded");await tx.pointLedger.create({data:{id:"pl_"+randomUUID(),userId:u.id,sourceType:"ad_session",sourceId:s.id,eventType:"ad_completed",points:s.rewardPoints,status:"available",description:`Sponsor ${s.campaign.sponsorName}`,availableAt:new Date()}});const acct=await tx.pointAccount.upsert({where:{userId:u.id},create:{userId:u.id,availablePoints:s.rewardPoints},update:{availablePoints:{increment:s.rewardPoints}}});await tx.adSession.update({where:{id:s.id},data:{completedAt:new Date(),rewardedAt:new Date(),status:"rewarded"}});return acct});return ok({rewarded:true,points:s.rewardPoints,balance:result})});
app.get("/v1/points/balance",async(req)=>{const u=await user(req);return ok(await prisma.pointAccount.upsert({where:{userId:u.id},create:{userId:u.id},update:{}}))});app.get("/v1/points/ledger",async(req)=>{const u=await user(req);return ok({items:await prisma.pointLedger.findMany({where:{userId:u.id},orderBy:{createdAt:"desc"}})})});
app.get("/v1/shop/items",async()=>ok({items:await prisma.shopItem.findMany({where:{status:"active"},orderBy:{pointsPrice:"asc"}})}));
app.post("/v1/shop/redeem",async(req:any)=>{const u=await user(req);const item=await prisma.shopItem.findUniqueOrThrow({where:{id:req.body.itemId}});const acct=await prisma.pointAccount.upsert({where:{userId:u.id},create:{userId:u.id},update:{}});if(acct.availablePoints<item.pointsPrice)return err("INSUFFICIENT_POINTS","Insufficient points",400).body;const order=await prisma.$transaction(async(tx)=>{await tx.pointAccount.update({where:{userId:u.id},data:{availablePoints:{decrement:item.pointsPrice},redeemedPoints:{increment:item.pointsPrice}}});await tx.pointLedger.create({data:{id:"pl_"+randomUUID(),userId:u.id,sourceType:"redemption",sourceId:item.id,eventType:"redeem",points:-item.pointsPrice,status:"completed",description:item.name,availableAt:new Date()}});return tx.redemptionOrder.create({data:{id:"red_"+randomUUID(),userId:u.id,itemId:item.id,pointsCost:item.pointsPrice,status:item.requiresReview?"pending_review":"approved",deliveryType:item.deliveryType,deliveryPayload:req.body.deliveryInfo}})});return ok({orderId:order.id,status:order.status})});app.get("/v1/redemptions",async(req)=>{const u=await user(req);return ok({items:await prisma.redemptionOrder.findMany({where:{userId:u.id}})})});app.get("/v1/redemptions/:id",async(req:any)=>ok({order:await prisma.redemptionOrder.findUnique({where:{id:req.params.id}})}));
function admin(req:any){if((req.headers.authorization||"")!==`Bearer ${process.env.ADMIN_TOKEN||"dev-admin-token"}`)throw new Error("Admin auth required")}
app.get("/admin/campaigns",async(req)=>{admin(req);return ok({items:await prisma.campaign.findMany()})});app.post("/admin/campaigns",async(req:any)=>{admin(req);return ok(await prisma.campaign.create({data:{id:"camp_"+randomUUID(),...req.body}}))});app.patch("/admin/campaigns/:id",async(req:any)=>{admin(req);return ok(await prisma.campaign.update({where:{id:req.params.id},data:req.body}))});app.get("/admin/shop/items",async(req)=>{admin(req);return ok({items:await prisma.shopItem.findMany()})});app.post("/admin/shop/items",async(req:any)=>{admin(req);return ok(await prisma.shopItem.create({data:{id:"item_"+randomUUID(),...req.body}}))});app.patch("/admin/shop/items/:id",async(req:any)=>{admin(req);return ok(await prisma.shopItem.update({where:{id:req.params.id},data:req.body}))});app.get("/admin/redemptions",async(req)=>{admin(req);return ok({items:await prisma.redemptionOrder.findMany({include:{item:true,user:true}})})});app.patch("/admin/redemptions/:id",async(req:any)=>{admin(req);return ok(await prisma.redemptionOrder.update({where:{id:req.params.id},data:req.body}))});app.get("/admin/users",async(req)=>{admin(req);return ok({items:await prisma.user.findMany({include:{account:true}})})});app.get("/admin/ledger",async(req)=>{admin(req);return ok({items:await prisma.pointLedger.findMany({orderBy:{createdAt:"desc"}})})});
const port=Number(process.env.PORT||3000);app.listen({port,host:"0.0.0.0"});
