#!/usr/bin/env node
import { Command } from "commander";import { randomUUID } from "node:crypto";import { CLI_VERSION } from "@9527/shared";import { ApiClient } from "./core/api-client.js";import { readConfig, updateConfig, writeConfig } from "./core/local-config.js";import { runWrapped } from "./core/command-wrapper.js";
const program=new Command();program.name("9527").version(CLI_VERSION);
program.command("init").action(async()=>{const c=readConfig();try{const api=new ApiClient();const d=await api.post<{userId:string;deviceId:string;apiToken:string}>("/v1/init",{deviceHash:c.deviceId||randomUUID(),os:process.platform,cliVersion:CLI_VERSION});writeConfig({...c,...d,adsEnabled:true,cliVersion:CLI_VERSION});console.log(`9527 initialized. userId=${d.userId}`)}catch(e:any){const d={userId:`user_${randomUUID()}`,deviceId:`dev_${randomUUID()}`,apiToken:`dev_${randomUUID()}`};writeConfig({...c,...d});console.log(`9527 initialized locally (API unavailable: ${e.message}).`)}});
program.command("run").allowUnknownOption(true).argument("[cmd...]","command").action(runWrapped);
program.command("balance").action(async()=>{try{const b=await new ApiClient().get<any>("/v1/points/balance");console.table(b)}catch(e:any){console.error(e.message);process.exitCode=1}});
program.command("shop").action(async()=>{try{const d=await new ApiClient().get<{items:any[]}>("/v1/shop/items");console.table(d.items)}catch(e:any){console.error(e.message);process.exitCode=1}});
program.command("redeem").argument("<itemId>").option("-e, --email <email>").action(async(itemId,opts)=>{try{const d=await new ApiClient().post<any>("/v1/shop/redeem",{itemId,deliveryInfo:{email:opts.email}});console.log(`Redemption created: ${d.orderId} (${d.status})`)}catch(e:any){console.error(e.message);process.exitCode=1}});
const cfg=program.command("config");cfg.command("get").argument("[key]").action(k=>{const c:any=readConfig();console.log(k?c[k]:JSON.stringify(c,null,2))});cfg.command("set").argument("<key>").argument("<value>").action((k,v)=>{const c:any=readConfig();c[k]=v==="true"?true:v==="false"?false:v;writeConfig(c);console.log("ok")});program.command("enable").action(()=>{updateConfig({adsEnabled:true});console.log("Sponsor rewards enabled.")});program.command("disable").action(()=>{updateConfig({adsEnabled:false});console.log("Sponsor rewards disabled.")});program.command("version").action(()=>console.log(CLI_VERSION));program.parse();
